### ISSUE TITLE
SlimerJS throws `Unable to load Atom` errors when driven by Selenium-Webdriver

### ISSUE THREAD

**Issue by jasonkarns** [laurentj/slimerjs#389]
Steps performed below manually via irb with selenium-webdriver gem loaded.

Using PhantomJS driver configuration for webdriver, but with an overridden path to point to slimerjs executable.
``` irb
irb> require 'selenium-webdriver'
=> true
irb> Selenium::WebDriver::PhantomJS.path = '/usr/local/bin/slimerjs'
=> "/usr/local/bin/slimerjs"
irb> driver = Selenium::WebDriver.for :phantomjs
=> #<Selenium::WebDriver::Driver:0x..fda95f7649456d66a browser=:phantomjs>
irb> driver.navigate.to "http://www.google.com
=> {}
irb> driver.find_element(:name, 'q')
Selenium::WebDriver::Error::WebDriverError: unexpected response, code=404, content-type="text/plain"
Error - Unable to load Atom 'find_element' from file 'undefined/third_party/webdriver-atoms/find_element.js'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/common.rb:85:in `create_response'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:635:in `execute'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:603:in `find_element_by'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/common/search_context.rb:61:in `find_element'
	from (irb):8
	from /usr/local/var/rbenv/versions/2.0.0-p481/bin/irb:12:in `<main>'
```

A similar error is raised if attempting to `execute_script`:

```
Selenium::WebDriver::Error::WebDriverError: unexpected response, code=404, content-type="text/plain"
Error - Unable to load Atom 'execute_script' from file 'undefined/third_party/webdriver-atoms/execute_script.js'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/common.rb:85:in `create_response'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:635:in `execute'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:360:in `executeScript'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/common/driver.rb:210:in `execute_script'
	from (irb):12
	from /usr/local/var/rbenv/versions/2.0.0-p481/bin/irb:12:in `<main>'
```

All of these steps work as expected when using PhantomJS (everything same as above but without the `.path` override)

**Comment by jasonkarns** [comment]
I should point out that the xulrunner does open, and it does indeed navigate to any web address requested. The only error is when attempting to use `find_element` or `execute_script`. (Other driver API methods not yet attempted)

**Comment by volvofixthis** [comment]
I found this problem too. Here my dirty solution... i copied modules dir from sources or you can extract it from omni.ja to you working dir. Now i fixed file in such way src/modules/ghostdriver/webdriver_atoms.js

var fs = require("fs"),
    atomsCache = {};

exports.get = function(atomName) {
    var atomFileName =  "modules/ghostdriver/third_party/webdriver-atoms/" + atomName + ".js";

    // Check if we have already loaded an cached this Atom
    if (!atomsCache.hasOwnProperty(atomName)) {
        try {
            atomsCache[atomName] = fs.read(atomFileName);
        } catch (e) {
            throw new Error("Unable to load Atom '"+atomName+"' from file '"+atomFileName+"'"+" working dir '"+fs.workingDirectory);
        }
    }

    return atomsCache[atomName];
};

after this all working ok. Maybe there is better solution

**Comment by laurentj** [comment]
Please test [the latest build](https://download.slimerjs.org/nightlies/0.10.0pre/), I think I fixed this issue. I move ghostdriver outside the omni.ja file.

**Comment by jasonkarns** [comment]
With latest build, slimer no longs starts from command line

```
$ slimerjs 
script is missing
```

and receive similar startup error in irb

```
irb(main):003:0> driver = Selenium::WebDriver.for :phantomjs
Selenium::WebDriver::Error::WebDriverError: unable to connect to phantomjs @ http://127.0.0.1:8910 after 20 seconds
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/phantomjs/service.rb:66:in `start'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/phantomjs/bridge.rb:39:in `initialize'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/common/driver.rb:62:in `new'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/common/driver.rb:62:in `for'
	from /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver.rb:84:in `for'
	from (irb):3
	from /usr/local/var/rbenv/versions/2.0.0-p481/bin/irb:12:in `<main>'
```

**Comment by volvofixthis** [comment]
can confirm this problem.

**Comment by laurentj** [comment]
In you example, you forgot to indicate command line parameter to launch webdriver. See all `–webdriver*` parameters [in the documentation](https://docs.slimerjs.org/nightly/configuration.html).

**Comment by jasonkarns** [comment]
I'm using selenium-webdriver to spin up slimer, which *does* pass the arguments. (I'm using slimer has a drop in replacement for phantom, so I'm expecting nothing to change between phantom and slimer except the path to the binary.)

selenium-webdriver passes the `--webdriver=<uri>` argument [here](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/phantomjs/service.rb#L93)

**Comment by volvofixthis** [comment]
we are talking about that even command line  "./slimerjs script.js" don't work.

**Comment by jasonkarns** [comment]
Ah, right. I wouldn't have expected `$ slimerjs` (with no args) to expose the webdriver stuff. But shouldn't it still spin up without error?

**Comment by rodzam** [comment]
Though marked as closed, this issue appears to persist. Please let me know if you'd like me to open a new issue.

Using Python 3.4.3, Selenium 2.53.4, and both the most recent stable version (0.10.1) and the nightly (Oct. 6 version of 1.0.0-pre) of SlimerJS, I'll run the following code:

```python
from selenium import webdriver
browser = webdriver.PhantomJS(executable_path="./slimerjs/slimerjs")
browser.get("https://slimerjs.org/")
browser.find_element(".download")
```

The SlimerJS window opens up nicely, it loads the page perfectly, but when it's time to find the element, I get the following exception:

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 745, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 165, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Error - Unable to load Atom 'find_element' from file 'undefined/third_party/webdriver-atoms/find_element.js'
```

Other functions, like `browser.save_screenshot("test.png")` work nicely.

**Comment by laurentj** [comment]
@rodzam please open a new issue.
